---
- name: DEPLOY BRANCH
  hosts: fortimanagers
  connection: httpapi
  collections:
    - fortinet.fortimanager
  gather_facts: yes

  vars:

  tasks:
    - include_vars: "../vars/enterprise1.yml"
    - include_vars: "../vars/enterprise1_branch1.yml"

    - name: GET MODEL DEVICE "{{ device_name }}" TO FORTISWITCH TEMPLATE "{{ fsw_name }}"
      fmgr_generic:
        method: get
        params:
          - url: "/pm/config/adom/{{ adom_name }}/obj/fsp/managed-switch/{{ fsw_sn }}"
            data:
              -
            scope member:
              - name: "{{ device_name }}"
                vdom: "{{ device_vdom_name }}"
