---
- name: FACTS
  hosts: fortimanagers
  gather_facts: yes
  connection: httpapi
  collections:
    - fortinet.fortimanager

  tasks:
    - include_vars: "../vars/enterprise1.yml"
    - include_vars: "../vars/enterprise1_branch1.yml"
    - name: Retrieve device
      fmgr_fact:
       facts:
         selector: 'devprof_system_dns'
         params:
           adom: "{{ adom_name }}"
           devprof: "branches_system_template"
         option:
           - 'get meta'
