---
- name: FACTS
  hosts: fortimanagers
  gather_facts: yes
  connection: httpapi
  collections:
    - fortinet.fortimanager

  tasks:
    - include_vars: "../vars/enterprise1.yml"
    - include_vars: "../vars/enterprise1_branch1.yml"
    - name: Retrieve device
      fmgr_fact:
       facts:
         selector: 'dvmdb_device'
         params:
           adom: "{{ adom_name }}"
           device: "fgt-Enterprise1-branch1"
         option:
           - 'get meta'
