- name: CREATE CLI SCRIPTS GROUPS
  fmgr_dvmdb_script:
        adom: "{{ adom_name }}"
        workspace_locking_adom: "{{ adom_name }}"
        state: present
        dvmdb_script:
           content: ""
           name: "{{ item.name }}"
           type: "{{ item.type }}"
           target: "{{ item.target }}"
           filter_hostname: ""
           desc: "CLI Script Group created via Ansible"
           filter_serial: ""

  with_items:
    - name: "{{ cli_script_group_name }}"
      type: "cligrp"
      target: "device_database"

- name: ADD MEMBERS TO SCRIPT GROUP
  fmgr_dvmdb_script_objectmember:
        adom: "{{ adom_name }}"
        workspace_locking_adom: "{{ adom_name }}"
        script: "{{ cli_script_group_name }}"
        state: present
        dvmdb_script_objectmember:
           name: "{{ item.name }}"
  with_items:
    - name: "001.purge.firewall.policies"
