- name: CREATE FORTISWITCH TEMPLATE "{{ fsw_name }}"
  fmgr_switchcontroller_managedswitch:
     workspace_locking_adom: "{{ adom_name }}"
     state: present
     adom: "{{ adom_name }}"
     switchcontroller_managedswitch:
        name: "{{ fsw_profile_name }}"
        _platform: "{{ fsw_platform }}"
        description: "FortiSwitch Template created via Ansible"
        ports:
          - port-name: port1
            vlan: [default]
            lldp-profile: [default]
          - port-name: port2
            vlan: [vlan_mgmt_fap]
            lldp-profile: [default]
          - port-name: port3
            vlan: [vlan_marketing]
            lldp-profile: [default]
          - port-name: port4
            vlan: [vlan_support]
            lldp-profile: [default]
          - port-name: port5
            vlan: [vlan_finance]
            lldp-profile: [default]
        switch-id: "{{ fsw_profile_name }}"
