- name: INITIALIST THE MEMBER LIST FOR CLI TEMPLATE GROUP "{{ cli_template_group_name }}"
  set_fact:
    member_list: []

- name: POPULATE THE MEMBER LIST FOR CLI TEMPLATE GROUP "{{ cli_template_group_name }}"
  set_fact:
    member_list: "{{ member_list + [ item ] }}"

  with_items:
    - 001.system.global
    - 002.system.interface
    - 003.system.dhcp.server
    - 004.system.interface.fsw
    - 005.system.dhcp.server.fsw
    - 006.system.interface.fap
    - 007.system.dhcp.server.fap
    - 008.router.static

- name: CREATE CLI TEMPLATE GROUP "{{ cli_template_group_name }}"
  fmgr_generic:
     method: "set"
     params:
       - url: "/pm/config/adom/{{ adom_name }}/obj/cli/template-group"
         data:
            -
              name: "{{ cli_template_group_name }}"
              description: "CLI Template Group created via Ansible"
              member: "{{ member_list }}"
