- name: ADD FIREWALL POLICIES IN POLICY PACKAGE "{{ ppkg_production }}"
  fortimgr_jsonrpc_request:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    method: add
    params: [
      {
        url: "/pm/config/adom/{{ adom_name }}/pkg/{{ ppkg_production }}/firewall/policy",
        data: {
          policyid: "{{ item.policyid }}",
          global-label: "{{ item.global_label }}",
          srcintf: "{{ item.srcintf }}",
          dstintf: "{{ item.dstintf }}",
          srcaddr: "{{ item.srcaddr }}",
          dstaddr: "{{ item.dstaddr }}",
          service: "{{ item.service }}",
          schedule: "{{ item.schedule }}",
          action: "{{ item.action }}",
          application-list: "{{ item.application_list }}",
          av-profile: "{{ item.av_profile }}",
          profile-protocol-options: "{{ item.profile_protocol_options }}",
          ssl-ssh-profile: "{{ item.ssl_ssh_profile }}",
          webfilter-profile: "{{ item.webfilter_profile }}",
          dnsfilter-profile: "{{ item.dnsfilter_profile }}",
          ips-sensor: "{{ item.ips_sensor }}",
          logtraffic: "{{ item.logtraffic }}",
          utm-status: enable,
          nat: enable,
        },
      },
      ]

  with_items:
    - policyid: 1
      global_label: "Outgoing Traffic"
      srcintf: [vlan_finance, vlan_marketing, vlan_support, "{{ local_switch }}"]
      dstintf: [virtual-wan-link]
      srcaddr: [all]
      dstaddr: [all]
      service: [ALL]
      schedule: [always]
      action: accept
      application_list: [default]
      av_profile: [default]
      profile_protocol_options: [default]
      ssl_ssh_profile: [certificate-inspection]
      #ssl_ssh_profile: [no-inspection]
      webfilter_profile: [default]
      dnsfilter_profile: [default]
      ips_sensor: [default]
      logtraffic: [all]
    - policyid: 2
      global_label: "Outgoing Wireless Traffic"
      srcintf: [ssid_finance, ssid_marketing, ssid_support]
      dstintf: [virtual-wan-link]
      srcaddr: [all]
      dstaddr: [all]
      service: [ALL]
      schedule: [always]
      action: accept
      application_list: [default]
      av_profile: [default]
      profile_protocol_options: [default]
      ssl_ssh_profile: [certificate-inspection]
      webfilter_profile: [default]
      dnsfilter_profile: [default]
      ips_sensor: [default]
      logtraffic: [all]
