- name: ENABLE AUTO-AUTHORIZE ON MODEL DEVICE "{{ device_name }}", INTERFACE fortilink"
  fortimgr_jsonrpc_request:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    method: set
    params: [
      {
        url: "/pm/config/device/{{ device_name }}/global/system/interface/fortilink",
        data: {
          auto-auth-extension-device: enable,
        },
      },
    ]

- name: ADD FORTISWITCH "{{ fsw_sn }}" TO MODEL DEVICE "{{ device_name }}"
  fortimgr_jsonrpc_request:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    method: add
    sleep: "{{ install_sleep_time }}"
    params: [
      {
        url: "/pm/config/device/{{ device_name }}/vdom/{{ device_vdom_name }}/switch-controller/managed-switch",
        data: {
          name: "{{ fsw_sn }}",
          switch-id: "{{ fsw_sn }}",
        },
        push: 1,
      },
    ]
