- name: ADD MODEL DEVICE "{{ device_name }}" with SN "{{ device_sn }}"
  fortimgr_jsonrpc_request:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    method: exec
    params: [
      {
        url: /dvm/cmd/add/device,
        data: {
          adom: "{{ adom_name }}",
          device: {
            name: "{{ device_name }}",
            sn: "{{ device_sn }}",
            adm_usr: admin,
            adm_pass: null,
            desc: "This Model Device has been added using Ansible!",
            "device action": add_model,
            mgmt_mode: fmgfaz,
            os_type: fos,
            os_ver: "6.0",
            mr: 2,
            patch: 4,
          },
          flags: [none],
        },
      },
      ]

- name: ENABLE AUTO LINK AND SET COORDINATES FOR DEVICE "{{ device_name }}"
  fortimgr_jsonrpc_request:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    method: set
    sleep: "{{ install_sleep_time }}"
    params: [
      {
        url: "/dvmdb/device/{{ device_name }}",
        data: {
          latitude: "{{ device_latitude }}",
          longitude: "{{ device_longitude }}",
          flags: [
            is_model,
            linked_to_model,
          ],
        },
      },
    ]
