---
- name: GET LOGS
  hosts: fmg_gcp
  connection: local
  gather_facts: false
  vars:
     demo_id: 42
     adom_name: "TEAM{{ demo_id }}"
     system_template_name: branches_system_template

  tasks:
    - name: GET SYSTEM TEMPLATE "{{ system_template_name }}" - FORTIANALYZER
      fortimgr_jsonrpc_request:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: get
        params: [
          {
            url: "/pm/config/adom/{{ adom_name }}/devprof/{{ system_template_name }}/device/profile/fortianalyzer",
            data: {
            },
          },
        ]
    
    - name: GET SYSTEM TEMPLATE "{{ system_template_name }}" - FORTIANALYZER SETTINGS
      fortimgr_jsonrpc_request:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: get
        params: [
          {
            url: "/pm/config/adom/{{ adom_name }}/devprof/{{ system_template_name }}/log/fortianalyzer/setting",
            data: {
            },
          },
        ]
