---
- name: GET LOGS
  hosts: fmg_gcp
  connection: local
  gather_facts: false
  vars:
  tasks:
    - name: GET MANAGED SWITCH - FGT
      fortimgr_jsonrpc_request:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        method: get
        params: [
          {
            url: "/pm/config/adom/{{ adom_name }}/obj/switch-controller/managed-switch",
            data: {
            },
          },
        ]
    
