- name: INITIALIZE META FIELDS FOR MODEL DEVICE "{{ device_name }}"
  fortimgr_jsonrpc_request:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    method: update
    params: [
      {
        url: "/dvmdb/device/{{ device_name }}",
        data: {
          "meta fields": {
            branch_number: "{{ branch_number | string}}",
            isp1_intf: "{{ isp1_intf }}",
            isp2_intf: "{{ isp2_intf }}",
            fortilink_intf: "{{ fortilink_intf }}",
            adom_name: "{{ adom_name }}",
          },
        },
      },
    ]
