- name: SET DEVICE "{{ device_name }}" HOSTNAME
  fortimgr_jsonrpc_request:
    host: "{{ ansible_host }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    method: set
    params: [
      {
        url: "/pm/config/device/{{ device_name }}/global/system/global",
        data: {
          hostname: "{{ device_name }}",	
        },
      },
    ]
