- name: ASSIGN MODEL DEVICE "{{ device_name }}" TO CLI TEMPLATE GROUP "{{ cli_template_group_name }}"
  fmgr_generic:
    method: add
    params:
     - url: "/pm/config/adom/{{ adom_name }}/obj/cli/template-group/{{ cli_template_group_name }}/scope member"
       data:
        -
          name: "{{ device_name }}"
          vdom: "{{ device_vdom_name }}"
