- name: REMOVE {{ fortilink_intf }} FROM INTERNAL TO FORTILINK
  fmgr_generic:
    workspace_locking_adom: "{{ adom_name }}"
    method: delete
    params:
     - url: "/pm/config/device/{{ device_name }}/global/system/virtual-switch/{{ local_switch }}/port/{{ fortilink_intf }}"
       data:

- name: UPDATE {{ fortilink_intf }} FROM INTERNAL TO FORTILINK
  fmgr_generic:
    workspace_locking_adom: "{{ adom_name }}"
    method: update
    params:
     - url: "/pm/config/device/{{ device_name }}/global/system/interface/fortilink"
       data:
         member: "{{ fortilink_intf }}"
         switch-controller-nac: ""

- name: INSTALL ON DEVICE {{ device_name }}
  fmgr_generic:
    workspace_locking_adom: "{{ adom_name }}"
    method: exec
    params:
     - url: "/securityconsole/install/device"
       data:
         adom: "{{ adom_name }}"
         scope:
           - name: "{{ device_name }}"
             vdom: "{{ device_vdom_name }}"
