- name: CREATE MODEL DEVICE "{{ device_name }}" with SN "{{ device_sn }}"
  fmgr_generic:
    workspace_locking_adom: "{{ adom_name }}"
    method: "exec"
    params:
      - url: "/dvm/cmd/add/device"
        data:
           adom: "{{ adom_name}}"
           device:
              adm_pass: [
               "admin"
               ]
              adm_usr: "admin"
              desc: "The device is added via Ansible"
              mgmt_mode: "fmgfaz"
              device action: "add_model"
              name: "{{ device_name }}"
              sn: "{{ device_sn }}"
              os_type: "fos"
              os_ver: "6.0"
              mr: 4
              patch: 4
           flags:
             - create_task
