- name: MOVE DEVICE "{{ device_name }}" IN GROUP "{{ spoke_group_name }}"
  fmgr_generic:
     method: add
     params:
       - url: "/dvmdb/adom/{{ adom_name }}/group/{{ spoke_group_name }}/object member"
         data:
            -
              name: "{{ device_name }}"
              vdom: "{{ device_vdom_name }}"
