---
- name: PROVISION FORTIMANAGER WITH SHARED COMPONENTS
  hosts: fmg_gcp
  connection: httpapi
  gather_facts: false

  vars:

  tasks:
     - name: GET SYSTEM STATUS
       fortimgr_jsonrpc_request:
          host: "{{ ansible_host }}"
          username: "{{ ansible_user }}"
          password: "{{ ansible_password }}"
          method: get
          params: [
            {
               url: "/sys/status",
               data: {
               },
            },
         ]

